run:
  name: "Lstm_prova"

data:
  dataset:
    csv_path: data/trajectories.csv
    total_qubits: 10
    used_qubits: 2
    time_steps: 1001
    n_traj: 400
    traj_fraction: 0.1

  windowing:
    input_seq_len: 200
    output_seq_len: 100
    stride: 20
    mode: seq2seq      

  split:
    seed: 42
    val_ratio: 0.2
    test_ratio: 0.15

model:
  name: "prova1"
  save_model: true
  type: "LSTM"
  variant: "SEQ2SEQ"
  decoder_mode: "STEP_WISE"  # "FULL_SEQ"  ,  "STEP_WISE"

  params:
    latent_dim: 128

  compile:
    optimizer: "adam"
    loss: "mse"
    metrics: ["mae"]


  inference:
    mode : "free_running"   # "teacher_forcing" | "free_running"
    start_mode: "zeros"    # "zeros" | "last_x"
    verbose : 0  # 0,1,2



training:
  verbose : 2
  batch_size: 32
  phases:
    - name: teacher_forcing
      epochs: 5

    # - name: masked_modeling
    #   epochs: 10
    #   mask_prob: 0.15
    #   # mask_scope: element     # time | element | feature
    #   # mask_mode: zero         # zero | constant | noise
    #   # mask_value: 0.0         # solo se constant
    #   # noise_sigma: 0.1        # solo se noise

    # - name: scheduled_sampling
    #   epochs: 5
    #   tf_ratio_start: 1.0
    #   tf_ratio_end: 0.2

  # Free-running evaluation 
  fr_eval:
    enabled: true  # enable/disable free-running eval callback
    split: test    # test | val 
    p_eval: 0.2    # value beetwen  > 0 e 1 for percentual 
    every_epochs: 1 # frequency of evaluation (in epochs)
  

plot:
  pred_all : true # TODO this is not usefull
  sample_index: [0,2,4]  # None = 0 , oppure una cosi = 1 oppure lista cosi []
  save_plots: true
  save_artifacts : true