data:
  dataset:
    csv_path: data/trajectories.csv
    total_qubits: 10
    used_qubits: 8
    time_steps: 1001
    n_traj: 400
    traj_fraction: 0.1

  windowing:
    input_seq_len: 400
    output_seq_len: 75
    stride: 30    

  split:
    seed: 42
    val_ratio: 0.2
    test_ratio: 0.15

model:
  name: "prova1"
  save_model: true
  type: "LSTM"
  variant: "SEQ2SEQ"
  decoder_mode: "STEP_WISE"  # "FULL_SEQ"  ,  "STEP_WISE"

  params:
    latent_dim: 128

  compile:
    optimizer: "adam"
    loss: "mse"
    metrics: ["mae"]
    run_eagerly: false
    learning_rate: 0.001
    clip_norm: 1.0

  inference:
    mode : "free_running"   # "teacher_forcing" | "free_running"
    start_mode: "last_x"    # "zeros" | "last_x"
    verbose : 0  # 0,1,2


training:
  verbose : 1
  batch_size: 64
  curriculum: [10, 10, 25] # [5,10,25,30,-1,50]   # number of elements = number of strategies if we dont use a specific temporal horizon  insert -1 
  # remember the number of epoch for each temporal horizon is decided by the specific strategy
  phases:

    - name: full_autoregressive
      epochs: 5
      gradient_through_time: false
      learning_rate: 0.0005
      clip_norm: 0.5

    - name: teacher_forcing
      epochs: 5 

    - name: masked_modeling
      epochs: 5
      mask_prob: 0.20
      learning_rate: 0.0005
      clip_norm: 0.7
      mask_scope: element     # time | element | feature
      mask_mode: zero         # zero | constant | noise
      mask_value: 0.0         # solo se constant
      noise_sigma: 0.1        # solo se noise

    # - name: full_autoregressive
    #   epochs: 5
    #   gradient_through_time: true
    #   learning_rate: 0.0003
    #   clip_norm: 0.5


    # - name: scheduled_sampling
    #   epochs: 8
    #   tf_ratio_start: 1.0
    #   tf_ratio_end: 0.5
    #   learning_rate: 0.0003
    #   clip_norm: 0.5
    #   # mode : lineare, esponenziale, inverse-sigmoid.
    #   # per_feature : true , false  
      
    # - name: full_autoregressive
    #   epochs: 5
    #   gradient_through_time: true
    #   learning_rate: 0.0001
    #   clip_norm: 0.3

  # free-running evaluation
  fr_eval:
    enabled: true
    split: val   # val || test 
    
    # p_eval => percentuage of the (val or test) split
    # out_steps can be 
    # out_steps => phase  where phase take horizon prediction determinated by a used strategy
    # out_steps => global where the horizon prediction are taken by output_seq_len
    # out_steps => [10,25,60,100] a list of horizon values insert by the programmer 
    probes:
      - name: fr_phase 
        out_steps: phase  
        every_epochs: 2
        p_eval: 0.8    

      - name: fr_target
        out_steps: global
        p_eval: 0.3
        every_epochs: end_of_phase

      - name: fr_curve
        out_steps: [10, 25, 50, 75] 
        p_eval: 0.2
        every_epochs: end_of_phase
  
plot:
  sample_index: [0,2,4]  # None = 0 , oppure una cosi = 1 oppure lista cosi []
  save_plots: true
  save_artifacts : true