tuning:
  seed: 42
  study_name: hybrid_lstm_lvl2
  n_trials: 20
  level: 2

  base_name: trn_sr

  # ONLY IF LEVEL 2
  level1_ref:
    study_name: study_lstm_lvl1 # which Level-1 study to anchor LR/clip to
    interval: 0.3 # +-30% interval for lvl2 tuning around Level-1 best

  monitors:
    #- "_fr_phase_loss_" # level 1
    - "val_loss" # level 2

  output:
    report_filename: report.csv

  sampler:
    # type: tpe # level 1
    type: nsga2 # level 2 (multi-objective)

  pruner:
    type: median
    n_startup_trials: 5
    n_warmup_steps: 3
